### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by Jolg42** [logdna/aws-cloudwatch#2]
The README is not really clear and should be updated (https://docs.logdna.com/docs/cloudwatch too)

What wasn't clear is:
- `1 - Create a new Lambda function and skip to the Configure function section` I guess this was about an old interface? It's impossible to find the Configure Function section see screenshot below
![screenshot 2018-07-20 at 17 02 20](https://user-images.githubusercontent.com/1328733/43009769-d9da4bb4-8c3e-11e8-930a-13711b3d0d3e.png)
- Before I could click on create, I had to create a role (this wasn't mentioned)
- Only after that I was able to click on Upload .zip from the `Code entry type` select input, and edit the handler see screenshot
![screenshot 2018-07-20 at 17 04 56](https://user-images.githubusercontent.com/1328733/43009877-2afdf46e-8c3f-11e8-91a0-7b119ef59585.png)
- And the environment vars below

**Comment by smusali** [comment]
This is good to know! We'll work on updating and making README better. Thanks for suggestions!

**Comment by ishi-geru** [comment]
Still the same README 👎

**Comment by smusali** [comment]
@ishi-geru @Jolg42 

We have improved and just updated our lambda function and docs - please, let us know if you have any other question! So sorry for being late! Thanks!
