### ISSUE TITLE
Minimum RAM? Timeout value?

### ISSUE THREAD

**Issue by Jolg42** [logdna/aws-cloudwatch#3]
This wasn't mentioned in the README but what do you recommend for these values?
This is a screenshot of the default values:
![screenshot 2018-07-20 at 17 08 33](https://user-images.githubusercontent.com/1328733/43010075-b12dd3b0-8c3f-11e8-855d-f09186583232.png)

**Comment by smusali** [comment]
It is not mentioned in the README because there is no need to configure this part for setting up lambda function. The most recommended thing is to leave it as it is.
