### ISSUE TITLE
It creates a new host in LogDNA Sources for each lambda instance!

### ISSUE THREAD

**Issue by Jolg42** [logdna/aws-cloudwatch#5]
This is getting crazy:

![screenshot 2018-07-23 at 10 51 01](https://user-images.githubusercontent.com/1328733/43067017-7b76cc3a-8e66-11e8-8a50-156339e08caf.png)

It's only for one small Lambda, I can't imagine the situation with more intensive Lambda 😅

**Comment by Jolg42** [comment]
Also the name of the host shouldn't be the name of the log but the name of the Lambda?

**Comment by smusali** [comment]
Hey @Jolg42, thanks for reporting the issue! I can see the problem and I will fix it asap.

**Comment by smusali** [comment]
@Jolg42, update Lambda function and ZIP file - set the lambda function again in the same way.

As a `hostname`, we have decided to take instance id which is the last part of `logStream` - so, for the logs coming from each instance will have separate `hostname` - you can use `LOGDNA_HOSTNAME` environment variable while setting the lambda function up if you want the `hostname` to be stable and the same for all logs sent by the same function.

Again, we are very thankful to you for mentioning this problem.
