### ISSUE TITLE
Terraform Module

### ISSUE THREAD

**Issue by tfhartmann** [logdna/aws-cloudwatch#6]
Hi! This is less of an issue, and more of  an FYI. 😄 we created a Terraform module for deploying this lambda and thought you folks might like to check it out. https://github.com/asicsdigital/terraform-aws-logdna-cloudwatch

**Comment by smusali** [comment]
Hey @tfhartmann ,

Thanks for the suggestion!

We may need to visit and check this module later in the future and get in touch with you!

Thanks again!

Have a good day,
Samir
